# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KeepMyDevices' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeepMyDevice
#  pod 'Wilddog'
  pod 'Alamofire', '~> 4.3'

  target 'KeepMyDevicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeepMyDevicesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
