# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KeepMyDevice' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeepMyDevice
  pod 'Wilddog'


  target 'KeepMyDeviceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeepMyDeviceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
